# Generated by Django 5.2.5 on 2025-10-17 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0002_streamplatform_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="platform",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to="watchlist_app.streamplatform",
            ),
            preserve_default=False,
        ),
    ]
