# Generated by Django 5.2.5 on 2025-10-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0005_review_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="avg_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="movie",
            name="rating_count",
            field=models.IntegerField(default=0),
        ),
    ]
